"""
MDP parameter templates and file generation for AISSM_BH.
"""

from typing import Dict, Any, Optional

MDP_TYPES = ["ions", "em", "nvt", "npt", "md"]

DEFAULT_MDP_PARAMS = {
    "ions": {
        "integrator": "steep",
        "emtol": 1000.0,
        "emstep": 0.01,
        "nsteps": 50000,
        "nstlist": 1,
        "cutoff-scheme": "Verlet",
        "ns_type": "grid",
        "coulombtype": "cutoff",
        "rcoulomb": 1.0,
        "rvdw": 1.0,
        "pbc": "xyz"
    },
    "em": {
        "integrator": "steep",
        "emtol": 1000.0,
        "emstep": 0.01,
        "nsteps": 50000,
        "nstlist": 1,
        "cutoff-scheme": "Verlet",
        "ns_type": "grid",
        "coulombtype": "PME",
        "rcoulomb": 1.0,
        "rvdw": 1.0,
        "pbc": "xyz"
    },
    "nvt": {
        "title": "Protein-ligand complex NVT equilibration",
        "define": "-DPOSRES",
        "integrator": "md",
        "nsteps": 50000,
        "dt": 0.002,
        "nstxout": 500,
        "nstvout": 500,
        "nstenergy": 500,
        "nstlog": 500,
        "continuation": "no",
        "constraint_algorithm": "lincs",
        "constraints": "h-bonds",
        "lincs_iter": 1,
        "lincs_order": 4,
        "cutoff-scheme": "Verlet",
        "ns_type": "grid",
        "nstlist": 10,
        "rcoulomb": 1.0,
        "rvdw": 1.0,
        "DispCorr": "EnerPres",
        "coulombtype": "PME",
        "pme_order": 4,
        "fourierspacing": 0.16,
        "tcoupl": "V-rescale",
        "tc-grps": "Protein Non-Protein",
        "tau_t": "0.1 0.1",
        "ref_t": "300 300",
        "pcoupl": "no",
        "pbc": "xyz",
        "gen_vel": "yes",
        "gen_temp": 300,
        "gen_seed": -1
    },
    "npt": {
        "title": "Protein-ligand complex NPT equilibration",
        "define": "-DPOSRES",
        "integrator": "md",
        "nsteps": 50000,
        "dt": 0.002,
        "nstxout": 500,
        "nstvout": 500,
        "nstenergy": 500,
        "nstlog": 500,
        "continuation": "yes",
        "constraint_algorithm": "lincs",
        "constraints": "h-bonds",
        "lincs_iter": 1,
        "lincs_order": 4,
        "cutoff-scheme": "Verlet",
        "ns_type": "grid",
        "nstlist": 10,
        "rcoulomb": 1.0,
        "rvdw": 1.0,
        "DispCorr": "EnerPres",
        "coulombtype": "PME",
        "pme_order": 4,
        "fourierspacing": 0.16,
        "tcoupl": "V-rescale",
        "tc-grps": "Protein Non-Protein",
        "tau_t": "0.1 0.1",
        "ref_t": "300 300",
        "pcoupl": "Parrinello-Rahman",
        "pcoupltype": "isotropic",
        "tau_p": 2.0,
        "ref_p": 1.0,
        "compressibility": 4.5e-5,
        "refcoord_scaling": "com",
        "pbc": "xyz",
        "gen_vel": "no"
    },
    "md": {
        "title": "Protein-ligand complex MD simulation",
        "integrator": "md",
        "nsteps": 5000000,
        "dt": 0.002,
        "nstxout": 5000,
        "nstvout": 5000,
        "nstenergy": 5000,
        "nstlog": 5000,
        "nstxout-compressed": 5000,
        "compressed-x-grps": "System",
        "continuation": "yes",
        "constraint_algorithm": "lincs",
        "constraints": "h-bonds",
        "lincs_iter": 1,
        "lincs_order": 4,
        "cutoff-scheme": "Verlet",
        "ns_type": "grid",
        "nstlist": 10,
        "rcoulomb": 1.0,
        "rvdw": 1.0,
        "DispCorr": "EnerPres",
        "coulombtype": "PME",
        "pme_order": 4,
        "fourierspacing": 0.16,
        "tcoupl": "V-rescale",
        "tc-grps": "Protein Non-Protein",
        "tau_t": "0.1 0.1",
        "ref_t": "300 300",
        "pcoupl": "Parrinello-Rahman",
        "pcoupltype": "isotropic",
        "tau_p": 2.0,
        "ref_p": 1.0,
        "compressibility": 4.5e-5,
        "pbc": "xyz",
        "gen_vel": "no"
    }
}


def create_mdp_file(mdp_type: str, params: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    """
    Create an MDP parameter file for GROMACS.

    Parameters
    ----------
    mdp_type : str
        Type of MDP file (ions, em, nvt, npt, md).
    params : dict, optional
        Override parameters.

    Returns
    -------
    dict
        Result with keys: ``success``, ``file_path``, ``mdp_type``, ``params``.
    """
    if mdp_type not in MDP_TYPES:
        return {"success": False, "error": f"Unknown MDP type: {mdp_type}"}

    mdp_params = DEFAULT_MDP_PARAMS[mdp_type].copy()
    if params:
        mdp_params.update(params)

    mdp_content = f"; {mdp_type}.mdp - Generated by AISSM_BH\n"
    for key, value in mdp_params.items():
        mdp_content += f"{key:<20} = {value}\n"

    file_path = f"{mdp_type}.mdp"
    with open(file_path, "w") as f:
        f.write(mdp_content)

    return {
        "success": True,
        "file_path": file_path,
        "mdp_type": mdp_type,
        "params": mdp_params
    }